### PR TITLE
use main repo client

### PR DESCRIPTION
**Pull request by wentevill**
1. remove `init`
2. use main repo client

### CODE REVIEW

**Comment by benjaminhuo** [comment]
@tpiperatgod would you help to review this?

**Comment by wentevill** [comment]
Need help testing `install`, `uninstall` and `demo` under linux because I don't have a linux machine.

**Review by tpiperatgod — APPROVED** [review]

**Comment by tpiperatgod** [comment]
Thanks, @wentevill . LGTM, and I will finish the testing on Linux asap and merge it if everything works.

**Comment by benjaminhuo** [comment]
Thanks @wentevill for the contribution

**Pull request merged**
