### PR TITLE
remove redundant https://

### PR DESCRIPTION
**Pull request by James-JLC**
the redundant https:// should be removed

### CODE REVIEW

**Comment by tpiperatgod** [comment]
Thanks, it seems you need to pass the CLA and DCO checks first. 🙂

**Review by tpiperatgod — APPROVED** [review]
lgtm

**Comment by James-JLC** [comment]
Signed-off-by: jilichao

**Comment by benjaminhuo** [comment]
@jilichao You need to squash and then sign your commits

- squash the 5 commits into 1:
git rebase -i squash head~5
image

https://www.git-tower.com/learn/git/faq/git-squash/

- re-sign the new commit:
git commit -s --amend

**Comment by benjaminhuo** [comment]
The commit has been messed up, maybe you can close this PR.
Fork the repo again and using a new branch to submit this PR
@jilichao

**Comment by James-JLC** [comment]
@benjaminhuo I submitted several times due to the internet issue before, and it should be fixed now.

**Pull request merged**
